### ISSUE TITLE
When "webp" is less than 6kb, it is not exported.(webpが6kb以下の時書き出しされません。)

### ISSUE THREAD

**Issue by solt-shio** [yat8823jp/themrishvite#3]
When "webp" is less than 6kb, it is not exported.

webpが6kb以下の時にコンパイルがされません。6kb以上だとされるようです。
publicに画像を入れた場合はコンパイルされますが、フォルダ階層を分けたいため、globを使った方法が知りたいです。

**Comment by syou97** [comment]
> When "webp" is less than 6kb, it is not exported.
> 
> webpが6kb以下の時にコンパイルがされません。6kb以上だとされるようです。 publicに画像を入れた場合はコンパイルされますが、フォルダ階層を分けたいため、globを使った方法が知りたいです。

**Comment by syou97** [comment]
build: {
    assetsInlineLimit:0,

で、解決しました。
https://vitejs.dev/config/build-options.html#build-assetsinlinelimit

**Comment by yat8823jp** [comment]
V1.2.1 で対応しました🙆‍♂️
ご報告ありがとう！
