### ISSUE TITLE
SCSSファイル内での相対パスについて

### ISSUE THREAD

**Issue by yukaorange** [yat8823jp/themrishvite#4]
参考にさせていただいております。
いきなりの質問で申し訳ありませんが、この開発環境において
scssファイルがmain.jsで読み込まれ、<style>タグ内にスタイルが入るところ、相対パスがテーマディレクトリを参照できないでいます。いろいろ設定をいじっているのですが、なにかいい方法はありそうでしょうか。

**Comment by yat8823jp** [comment]
@yukaorange vite.config に設定している変数 themePath にテーマディレクトリのパスを記載し、どうファイルの63行目で CSS の変数へ値を渡しています。
そのため、css で画像を指定する際に _base.scss に記載のように
```
background: url( $base-dir + 'assets/images/aig-ai20221111066-xl_TP_V.jpg' );
```
という形で変数を書き込む必要があります。
これを使って画像がでているか確認してみてください。
もしこれを使っているのに出ない場合はバグだと思うのでまた教えてもらえると嬉しいです。
